# docker-compose.yml

services:
  # =========================
  # 🧠 Backend (Laravel)
  # =========================
  backend:
    build: ./warehouse-api
    container_name: warehouse_api
    ports:
      - "8000:80"
    volumes:
      - ./warehouse-api:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      SANCTUM_STATEFUL_DOMAINS: localhost:3000

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: warehouse
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network  

  # =========================
  # ⚛️ Frontend (React)
  # =========================
  frontend:
    build: ./warehouse-frontend
    container_name: warehouse_frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./warehouse-frontend:/app
    command: ["npm", "start"]
    environment:
      - REACT_APP_API_URL=http://localhost:8000/v1/api
    depends_on:
      - backend
    networks:
      - app_network 

  # =========================
  # 🗄️ MySQL Database
  # =========================
  mysql:
    image: mysql:8
    container_name: warehouse_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: warehouse
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - app_network

# =========================
# 📦 Shared volumes & network
# =========================
volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
